synth_name: 'Caio Casiotone MT-11'
presets:
  #- piano
  #- electic piano
  #- harp
  - pipe organ
  - organ
  - accordion
  - violin
  - clarinet
notes:
  - F#3
  - F#4
  - F#5
settings:
  - vibrato
